export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST'
export const All_PRODUCTS_SUCCESS = 'All_PRODUCTS_SUCCESS'
export const All_PRODUCTS_FAIL = 'All_PRODUCTS_FAIL'



export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'




export const CLEAR_ERRORS = 'CLEAR_ERRORS'